
<?php
/**
 * Copyright © Exocortex, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ?>
<?php
$product = $block->getProduct();
?>
<head>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.2/semantic.min.css">
</head>
<div id="app-loader" style="width:100%;text-align:center;"><img src="https://i.redd.it/ounq1mw5kdxy.gif"/></div>
<div class="" data-role="clara-player" id="clara-player" style="height:auto">
  <div id="root"></div>
  <pre id="order-configuration" style="display:none">CONFIGURATION</pre>
</div>
<div data-role="clara-panelControl" id="clara-panelControl"></div>
<script type="text/x-magento-init">
  {
    "[data-role=clara-panelControl]": {
      "clara_configurator": {
        "optionConfig"  : <?php /* @escapeNotVerified */ echo $block->getJsonConfig()?>,
        "submitUrl"     : <?php /* @escapeNotVerified */ echo json_encode($block->getSubmitUrl($product))?>,
        "productId"     : <?php /* @escapeNotVerified */ echo json_encode($product->getId())?>,
        "localeCode"    : <?php /* @escapeNotVerified */ echo json_encode($block->getLanguage())?>,
        "customerName"  : <?php /* @escapeNotVerified */ echo json_encode($block->getLoggedinCustomerName())?>
      }
    }
  }
</script>
<div id="clara-form-configurations-wrapper"></div>
